name: Run Backend
on:
  push:
    paths:
      - 'trigger.txt'
jobs:
  run-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Добавляем права на запись в репозиторий
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install express ytdl-core tiktok-scraper cors
      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
      - name: Run server
        run: node server.js &
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      - name: Commit backend-url.json
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add backend-url.json
          git commit -m "Update backend-url.json" || echo "No changes to commit"
          git push
      - name: Keep workflow alive
        run: sleep 3600 # Keep server running for 1 hour
